name: CI
on:
  - push
  - pull_request

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        uses: kleidukos/get-tested@v0.1.9.1
        with:
          cabal-file: ban-instance.cabal
          ubuntu-version: '24.04'

  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'

      - name: Write cabal.project
        run: |
          cat > cabal.project <<EOF
          packages: .
          documentation: True
          tests: True
          EOF

      - run: cabal update
      - run: cabal freeze

      - uses: actions/cache@v5
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal build all
      - run: cabal test all --test-show-details=direct
      - run: cabal haddock all
      - run: cabal check
      - run: cabal sdist
